### ISSUE TITLE
list of differences between versions

### ISSUE THREAD

**Issue by CSGalloway** [igorlogius/bookmark-branch-porter#6]
**Is your feature request related to a problem? Please describe.**
Not really a problem. Just wanted to know if there is a way to view the differences between versions?

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Maybe a change log file would be good,  Lists the firt release at the bottom then as you go up in the file - you get more recent releases.

**Additional context**
N/A

**Comment by igorlogius** [comment]
Currently there is only the commit logs (and the release comments,  which are a subset of the commit logs). At the current time i dont intend to maintain an addional changelog file. Sorry.
