### ISSUE TITLE
Getting InvalidCharacterError on HTML export

### ISSUE THREAD

**Issue by lionkmp** [igorlogius/bookmark-branch-porter#7]
First, thank you for the plugins, this looks very promising.

When I try to export, I get this message **Export failed (InvalidCharacterError: String contains an invalid character)** this depends on which folder I want to export, so I think this is related to some local (Hungarian) letters or other special characters in the data. Meaning,I can export some folders, but most of my folders I cannot. While JSON output works for all.

Please note that output filename uses the folder name, so in Hungarian the root folder is exported as: "export -- Könyvjelzők menü.json"  - which already contains a "special character". (JOSN works., HTML not)

**To Reproduce**
1. Just export, and either it will work or not, based on Characters in that folder.

**Expected behavior**
Export any data.

**Desktop**
 - OS: Ubuntu Linux 20.04
 - Browser LibreWollf (Firefox)
 - Version 115.0.2-2
- Export plugin version: 1.3.10

Thanks in advance. Please let me know if you need detailed test of **exactly** which name or entry fails. But since most of my folders fail, it should be easy to find. :)

**Comment by igorlogius** [comment]
Should be fixed with `1.3.12`.

**Comment by lionkmp** [comment]
Works perfect, thank you for the quick fix!
