### ISSUE TITLE
Better HTML format

### ISSUE THREAD

**Issue by lionkmp** [igorlogius/bookmark-branch-porter#8]
When I export as HTML, it outputs the standard Firefox/Netscape HTML file, same as exported by the browser itself. (In Bookmarks manager.)

```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
```

This file format is quite useless for external processing, or at least not easy to process. E.g. since it's not an XHTML, this cannot be used as data for XSLT work. Many tags are uppercase, DT tags are not closed, and so on.

I tried your plugin in hope it would export a format that I can process further easier. I.e. a modern HTML file, not something that is from Netscape's time. ;-)

Please consider.

However if you are using the same API as Bookmarks Manager, then probably this is not possible.

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to open this issue.

The Netscape HTML output is especially designed to work with firefox's built-in bookmark import. So i wont be making any changes to it.

And for post processing, i think the JSON output format is sufficient,  which you can rather easily convert to XHTML or direclty use a tool like `jq` on to filter/manipulate the data in any way you want. 

While it is doable to add more output formats, i dont see the necessity for it at the moment, sorry.

**Comment by lionkmp** [comment]
ok, no worries, thank you. HTML-Tidy also solved all my problems.., even faster than processing the JSON. ;-) (got a rid of IKON files, and cleaned up the HTML code for future-proof storage)

tidy --wrap 0 -i --doctype html5 --strict-tags-attributes yes --drop-proprietary-attributes yes -clean -asxhtml
